name: Build project with Maven
on:
  pull_request:
  schedule:
  - cron: '2 2 * * 1-5' # run nightly master builds on weekdays

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin@v2
    - name: Java setup
      uses: actions/setup-java@78078da0cd035d0d177cc2cb696e05d96fba7d11 # pin@v1
      with:
        java-version: 17
    - name: Cache
      uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # pin@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Run Maven
      run: mvn -B clean verify com.mycila:license-maven-plugin:check
